[versions]
junit-jupiter = "5.12.1"
kotlin = "2.2.0"
kotest = "5.9.1"
ktlint = "1.7.1"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
kotlin-serialization-jvm = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "7.2.1" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.1" }
jreleaser = { id = "org.jreleaser", version = "1.19.0" }

[bundles]
kotest = ["kotest-assertions"]
